EVE/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EVE.Data;
using EVE.Models;
using Microsoft.AspNetCore.Authorization;

namespace EVE.Controllers
{
    [Authorize]
    public class CartsController : Controller
    {
        private readonly EVEContext _context;

        public CartsController(EVEContext context)
        {
            _context = context;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var eVEContext = _context.Cart.Include(c => c.Member);
            return View(await eVEContext.ToListAsync());
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .Include(c => c.Member)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            ViewData["Memberid"] = new SelectList(_context.Member, "MemberID", "Address");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Memberid,Quantity,TotalPrice")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Memberid"] = new SelectList(_context.Member, "MemberID", "Address", cart.Memberid);
            return View(cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            ViewData["Memberid"] = new SelectList(_context.Member, "MemberID", "Address", cart.Memberid);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Memberid,Quantity,TotalPrice")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Memberid"] = new SelectList(_context.Member, "MemberID", "Address", cart.Memberid);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .Include(c => c.Member)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cart = await _context.Cart.FindAsync(id);
            _context.Cart.Remove(cart);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
            return _context.Cart.Any(e => e.Id == id);
        }
    }
}

EVE/Controllers/FavoritesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EVE.Data;
using EVE.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;


namespace EVE.Controllers
{
    [Authorize]
    public class FavoritesController : Controller
    {
        private readonly EVEContext _context;

        public FavoritesController(EVEContext context)
        {
            _context = context;
        }

        // GET: Favorites
        public async Task<IActionResult> Index()
        {
            var eVEContext = _context.Favorite.Include(f => f.Member);
            return View(await eVEContext.ToListAsync());
        }

        // GET: Favorites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favorite = await _context.Favorite
                .Include(f => f.Member)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favorite == null)
            {
                return NotFound();
            }

            return View(favorite);
        }

        // GET: Favorites/Create
        public IActionResult Create()
        {
            ViewData["Memberid"] = new SelectList(_context.Member, "MemberID", "Address");
            return View();
        }

        // POST: Favorites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Memberid,Quantity,TotalPrice")] Favorite favorite)
        {
            if (ModelState.IsValid)
            {
                _context.Add(favorite);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Memberid"] = new SelectList(_context.Member, "MemberID", "Address", favorite.Memberid);
            return View(favorite);
        }

        // GET: Favorites/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favorite = await _context.Favorite.FindAsync(id);
            if (favorite == null)
            {
                return NotFound();
            }
            ViewData["Memberid"] = new SelectList(_context.Member, "MemberID", "Address", favorite.Memberid);
            return View(favorite);
        }

        // POST: Favorites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Memberid,Quantity,TotalPrice")] Favorite favorite)
        {
            if (id != favorite.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(favorite);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavoriteExists(favorite.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Memberid"] = new SelectList(_context.Member, "MemberID", "Address", favorite.Memberid);
            return View(favorite);
        }

        // GET: Favorites/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favorite = await _context.Favorite
                .Include(f => f.Member)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favorite == null)
            {
                return NotFound();
            }

            return View(favorite);
        }

        // POST: Favorites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var favorite = await _context.Favorite.FindAsync(id);
            _context.Favorite.Remove(favorite);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FavoriteExists(int id)
        {
            return _context.Favorite.Any(e => e.Id == id);
        }
    }
}

EVE/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EVE.Data;
using System.Net.Http;
using System.IO;
using Newtonsoft.Json;
using System.Net;
using System.Xml.Linq;
using System.Web.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace EVE.Controllers
{
    public class Location
    {
        [JsonProperty("lat")]
        public string lat;
        [JsonProperty("lng")]
        public string lng;
        [JsonProperty("address")]
        public string address;

        public Location(string lat, string lng,string address)
        {
            this.lat = lat;
            this.lng = lng;
            this.address = address;
        }
    }
    public class StoresController : Controller
    {
        private readonly EVEContext _context;
        private readonly HttpClient client;
        private List<Location> storesLocation;

        public StoresController(EVEContext context)
        {
            _context = context;
            storesLocation = new List<Location>();
        }


        private void GetStoreCoor(string street, string city, string countrey, string housenumber)
        {

            string address = street + "," + housenumber + "," + city + "," + countrey;
            string address2 = street + " " + housenumber + " " + city + " " + countrey;
            string apiKey = "AIzaSyDVuiJ4kCTsVZkbihbJOhBO2Cm0qFAssJw";
            string requestUri = string.Format("https://maps.googleapis.com/maps/api/geocode/xml?key={1}&address={0}&sensor=false", Uri.EscapeDataString(address), apiKey);

            WebRequest request = WebRequest.Create(requestUri);
            WebResponse response = request.GetResponse();
            XDocument xdoc = XDocument.Load(response.GetResponseStream());

            XElement result = xdoc.Element("GeocodeResponse").Element("result");
            XElement locationElement = result.Element("geometry").Element("location");
            XElement lat = locationElement.Element("lat");
            XElement lng = locationElement.Element("lng");
            storesLocation.Add(new Location(lat.Value, lng.Value, address2));
      



        }
        // GET: Stores
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stores.ToListAsync());
        }

        // GET: Stores/Stores
        public async Task<IActionResult> Stores()
        {
            foreach (Stores store in _context.Stores.ToList())
            {
                GetStoreCoor(store.street, store.city, store.countrey, store.houseNumber);
            
            }
            ViewBag.storesLocation = storesLocation.ToArray();
            ViewBag.storesaddress = _context.Stores.ToList();

            return View(await _context.Stores.ToListAsync());
        }

        // GET: Stores/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stores = await _context.Stores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stores == null)
            {
                return NotFound();
            }

            return View(stores);
        }

        // GET: Stores/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,countrey,city,street,houseNumber")] Stores stores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(stores);
        }

        // GET: Stores/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stores = await _context.Stores.FindAsync(id);
            if (stores == null)
            {
                return NotFound();
            }
            return View(stores);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,countrey,city,street,houseNumber")] Stores stores)
        {
            if (id != stores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoresExists(stores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stores);
        }

        // GET: Stores/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stores = await _context.Stores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stores == null)
            {
                return NotFound();
            }

            return View(stores);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stores = await _context.Stores.FindAsync(id);
            _context.Stores.Remove(stores);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StoresExists(int id)
        {
            return _context.Stores.Any(e => e.Id == id);
        }
    }
}

EVE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EVE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>


    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div href="mobile-menu">
                    <button class="main-menu"><i class="bi bi-list"></i>Menu</button>
                    <ul>
                        <a class="mobile-menu-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a> 
                        <a class="mobile-menu-link" asp-area="" asp-controller="ProductTypes" asp-action="Index">ProductTypes</a>
                    </ul>
                </div>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EVE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="nav-container navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div class="leftnav">
                        <div class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </div>
                    </div>
                    <div>
                        <input type="text" placeholder="Hey Girl, What are you looking for?" oninput="searchProduct()" />
                        <i class="bi bi-search"></i>
                    </div>
                    <div class="shopping-btn">
                        <div class="nav-item right-nav">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carts" asp-action="Index"><i class="bi bi-cart"></i></a>
                        </div>
                        <div class="nav-item right-nav">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Favorites" asp-action="Index"><i class="bi bi-heart"></i></a>
                        </div>
                        <div class="members-btn">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <div class="nav-item user-btn">

                                    <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Register">Sign Up </a>
                                </div>

                                <div class="nav-item user-btn">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Login">Login</a>
                                </div>
                            }
                            else
                            {

                                <div class="nav-item user-btn">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Logout">Logout</a>
                                </div>
                            }
                            </div>
                    </div>
                </div>
                </div>
        </nav>
    </header>
    <button onclick="getLocation()" class="get-weather-btn"><i class="bi bi-thermometer"></i>My Current Weather </button>
    <div id="demo"></div>



    <div class="container" style="background-color: #f2efe8;">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <hr />
    <div class="bottom" id="bottom" style=" display: flex; flex-direction: row; justify-content: space-between; width: 100%; padding:20px;">
        <div class="footerList" id="aboutUs">
            <h3>About Us</h3>
            <a class="about"  asp-area="" asp-controller="Home" asp-action="About">About</a>  <br>
            <a class="developers" asp-area="" asp-controller="Home" asp-action="Developers">Developers</a> <br>
        </div>
        <div class="footerList" id="termsOfUse">
            <h3>Terms Of Use</h3>
            <a class="websiteTerms" asp-area="" asp-controller="Home" asp-action="WebsiteTerms">Website Terms</a> <br>
            <a class="shippingTerms" asp-area="" asp-controller="Home" asp-action="Shipping">Shipping Terms</a> <br>
            <a class="privacyPolicy" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
        </div>
        <div class="footerList" id="contactUs">
            <h3>Contact Us</h3>
            <div>
                <p>Email: EVE@gmail.com</p>
                <p>Call us: 03-963-4000</p>
                <p>Address: Elie Wiesel 2 (The College Of Management)</p>
            </div>
            <a class="message" asp-area="" asp-controller="Home" asp-action="Contact">Leave a Message</a>
            <br />
            <a class="ourbrunches " asp-area="" asp-controller="Stores" asp-action="Stores">Our Brunches</a>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EVE - Coded by Yarden, Raz, Itai and Aviv.
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        var x = document.getElementById("demo");

        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition);
            } else {
                x.innerHTML = "Geolocation is not supported by this browser.";
            }
        }

        function showPosition(position) {
            const locationk = "http://dataservice.accuweather.com/locations/v1/cities/geoposition/search?apikey=jVJocZJyoDevTNB1Otg2AHap0mSydbs9&q=(31.961020%2C34.801620)";
            const forecasts = "http://dataservice.accuweather.com/forecasts/v1/daily/1day/{locationk}?apikey=jVJocZJyoDevTNB1Otg2AHap0mSydbs9";


            x.innerHTML = "Latitude: " + position.coords.latitude +
                "<br>Longitude: " + position.coords.longitude;
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>